services:
  hyvor-relay-backend:
    container_name: hyvor-relay-backend
    build:
      context: .
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      #- ../internal:/app/backend/vendor/hyvor/internal:ro
      # - ./shared:/app/shared
    labels:
      traefik.enable: true
      # backend
      traefik.http.routers.hyvor-relay-backend.rule: Host(`relay.hyvor.dev`)
      traefik.http.routers.hyvor-relay-backend.entrypoints: https
      traefik.http.routers.hyvor-relay-backend.tls: true
      traefik.http.routers.hyvor-relay-backend.service: hyvor-relay-backend
      # service
      traefik.http.services.hyvor-relay-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    healthcheck:
      test: ls
      disable: true

networks:
  hyvor-network:
    external: true
