services:
  frontend:
    container_name: hyvor-relay-frontend
    build:
      context: .
      target: frontend-dev
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/static:/app/frontend/static
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/bun.lock:/app/frontend/bun.lock
      - ./frontend/tsconfig.json:/app/frontend/tsconfig.json
      - ./frontend/svelte.config.js:/app/frontend/svelte.config.js
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-relay-frontend.rule: Host(`relay.hyvor.localhost`)
      traefik.http.routers.hyvor-relay-frontend.entrypoints: https
      traefik.http.routers.hyvor-relay-frontend.tls: true
      traefik.http.routers.hyvor-relay-frontend.middlewares: vite-retry@file
      traefik.http.services.hyvor-relay-frontend.loadbalancer.server.port: 80

    networks:
      - hyvor-network

  backend:
    container_name: hyvor-relay-backend
    build:
      context: .
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      - ../internal:/app/backend/vendor/hyvor/internal:ro
      # - ./shared:/app/shared
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-relay-backend.rule: Host(`relay.hyvor.localhost`) && PathPrefix(`/api`)
      traefik.http.routers.hyvor-relay-backend.entrypoints: https
      traefik.http.routers.hyvor-relay-backend.tls: true
      traefik.http.routers.hyvor-relay-backend.service: hyvor-relay-backend
      traefik.http.services.hyvor-relay-backend.loadbalancer.server.port: 80
    networks:
      - hyvor-network
    healthcheck:
      test: ls
      disable: true
    logging:
      driver: loki
      options:
        loki-url: "http://loki.localhost:3100/loki/api/v1/push"
        loki-retries: "2"
        loki-max-backoff: "800ms"
        loki-timeout: "1s"
        keep-file: "true"
        mode: non-blocking

  worker:
    container_name: hyvor-relay-worker
    image: cosmtrek/air
    working_dir: /worker
    volumes:
      - ./worker/:/worker/
    environment:
      GO_SYMFONY_URL: http://hyvor-relay-backend
    networks:
      - hyvor-network
    ports:
      - "10025:1025"
      - "5353:53/udp"
    logging:
      driver: loki
      options:
        loki-url: "http://loki.localhost:3100/loki/api/v1/push"
        loki-retries: "2"
        loki-max-backoff: "800ms"
        loki-timeout: "1s"
        keep-file: "true"
        mode: non-blocking

networks:
  hyvor-network:
    external: true
