monolog:
  handlers:
    main:
      type: stream
      path: php://stderr
      level: "%env(LOG_LEVEL)%"
      formatter: monolog.formatter.json

when@test:
  monolog:
    handlers:
      test:
        type: test
        level: info