services:
  postgres:
    container_name: postgres
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyvor_post_testing
    networks:
      - ci

networks:
  ci:
    external: true
