{
 "title": "Hyvor Relay",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({job=~\"hyvor-relay.*\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"hyvor-relay\"},instance)"
    }
   },
   {
    "name": "info_instance_domain",
    "query": {
     "query": "label_values(relay_info{job=\"$job\"},instance_domain)"
    }
   },
   {
    "name": "info_env",
    "query": {
     "query": "label_values(relay_info{job=\"$job\"},env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"font-size:16px\">\n<img \n src=\"https://hyvor.com/api/public/logo/relay.svg\"\n width=\"25\"\n /> Hyvor Relay\n </p>\n\n <hr />\n\n<h3>${info_instance_domain}</h3>\n\nenv: <strong>${info_env}</strong> <br />\nversion: <strong>${info_env}</strong>"
   }
  },
  {
   "title": "Servers",
   "type": "stat",
   "description": "Total number of servers in this Hyvor Relay Instance",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Workers",
   "type": "stat",
   "description": "Total number of API workers",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workers_api_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email Workers",
   "type": "stat",
   "description": "Total number of email workers",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workers_email_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook Workers",
   "type": "stat",
   "description": "Total number of email workers",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workers_webhook_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Mail Workers",
   "type": "stat",
   "description": "Total number of incoming mail workers",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workers_incoming_mail_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Send Attempts",
   "type": "stat",
   "description": "Total Number of Send Attempts (includes deferred, bounced and accepted)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(email_send_attempts_total{job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted Sends",
   "type": "stat",
   "description": "Number of send attempts in the selected time range that were accepted by the recipient server successfully.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(email_send_attempts_total{status=\"accepted\",job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deferred Sends",
   "type": "stat",
   "description": "Number of send attempts in the selected time range that were deferred to be tried later.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(email_send_attempts_total{status=\"deferred\", job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bounced Sends",
   "type": "stat",
   "description": "Number of send attempts in the selected time range that failed permanently.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(email_send_attempts_total{status=\"bounced\", job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send Attempts by Queue",
   "type": "timeseries",
   "description": "How many send attempts were tried per second for each queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(email_send_attempts_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (queue_name)",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  },
  {
   "title": "Failed Attempts by Queue",
   "type": "timeseries",
   "description": "How many send attempts were failed per second for each queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(email_send_attempts_total{job=\"$job\", status=\"bounced\",instance=~\"$instance\"}[$__rate_interval])) by (queue_name)",
     "legendFormat": "{{ queue_name }}"
    }
   ]
  },
  { "title": "Globals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "PostgreSQL Connections",
   "type": "timeseries",
   "description": "Number of open PostgreSQL connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pgsql_connections{job=\"$job\"}",
     "legendFormat": "Connections"
    },
    {
     "expr": "pgsql_max_connections{job=\"$job\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "Pending Emails in Queue",
   "type": "timeseries",
   "description": "Number of pending emails in each queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "email_queue_size{job=\"$job\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Webhooks",
   "type": "timeseries",
   "description": "Total webhook sending rate, by status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(webhook_deliveries_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sent Webhooks",
   "type": "stat",
   "description": "Total number of sent webhooks (success, failed, and deferred)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(webhook_deliveries_total{job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Webhooks",
   "type": "stat",
   "description": "Number of webhooks that were successfully sent (server responded with 2xx)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(webhook_deliveries_total{status=\"success\",job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deferred Webhooks",
   "type": "stat",
   "description": "Number of webhooks deferred to be retried later",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(webhook_deliveries_total{status=\"deferred\", job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Webhooks",
   "type": "stat",
   "description": "Number of failed webhooks (after all retries).",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(webhook_deliveries_total{status=\"failed\", job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "DNS Queries",
   "type": "timeseries",
   "description": "Successful (found) DNS queries rate by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(dns_queries_total{job=\"$job\",status=\"found\",instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DNS Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(dns_queries_total{job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful DNS Queries",
   "type": "stat",
   "description": "DNS queries that were successfully resolved",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(dns_queries_total{status=\"found\",job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NX DNS Queries",
   "type": "stat",
   "description": "Number of DNS queries that could not be resolved",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(dns_queries_total{status=\"not_found\", job=\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Incoming Mails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Incoming Mails",
   "type": "timeseries",
   "description": "Rate of incoming mails by type (bounce, fbl, unknown)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(incoming_emails_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Incoming Mails",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(incoming_emails_total{job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bounce Mails",
   "type": "stat",
   "description": "Number of bounce mails received",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(incoming_emails_total{type=\"bounce\",job=\"$job\",instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedback Loop Mails",
   "type": "stat",
   "description": "Number of Feedback Loop (complaint) emails received",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(incoming_emails_total{type=\"fbl\", job=\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unknown Mails",
   "type": "stat",
   "description": "Number of unknown (unparsable) emails received",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(incoming_emails_total{type=\"unknown\", job=\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_total{job=\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "table",
   "description": "Requests by Endpoint",
   "gridPos": { "h": 16, "w": 8, "x": 9, "y": 61 },
   "targets": [
    {
     "expr": "sort_desc(floor(sum by(endpoint) (increase(http_requests_total{job=\"$job\",instance=~\"$instance\"}[$__range]))))",
     "legendFormat": "Endpoint"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 61 },
   "targets": [
    {
     "expr": "sort_desc(sum(max_over_time(http_requests_total{job=\"$job\",instance=~\"$instance\"}[$__range])- min_over_time(http_requests_total{job=\"$job\",instance=~\"$instance\"}[$__range])) by (status))",
     "legendFormat": "Endpoint"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Per second rate",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "500 Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_total{job=\"$job\",instance=~\"$instance\",status=\"500\"}[$__range])))",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}