on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip and Upload Deploy Folder
        run: |
          ./deploy/zip.sh
          gh release upload ${{github.event.release.tag_name}} deploy/deploy.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}